### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chrisbutcher**
Excellent ebook. Thank you! I noticed one small typo so far.

### CODE REVIEW

**Comment by chrisbutcher** [comment]
cc: @cfsamson

**Comment by cfsamson** [comment]
@chrisbutcher I'm glad to hear you enjoy it, and thanks for the catch!

**Comment by chrisbutcher** [comment]
👋 @cfsamson do you plan to merge this into your article?

**Comment by cfsamson** [comment]
@chrisbutcher I've already fixed it. Since the PR is made to your fork and not to the original repo I can't merge it directly (and I can't close the issue either). I assumed that was intentional :)

I just corrected it straight away in the gitbook UI since I had to make som corrections anyway: https://cfsamsonbooks.gitbook.io/epoll-kqueue-iocp-explained/part-1-an-express-explanation

**Comment by chrisbutcher** [comment]
Ah thanks! :) I meant to point my PR at your master branch. All good thank you!

**Pull request closed without merging**
